---
keystore:
  File: /home/jerry/workspace/web3/sui/node-walrus-example/config/sui.keystore
envs:
  - alias: testnet
    rpc: 'https://fullnode.testnet.sui.io:443'
    ws: ~
    basic_auth: ~
  - alias: mainnet
    rpc: 'https://fullnode.mainnet.sui.io:443'
    ws: ~
    basic_auth: ~
active_env: testnet
active_address: '0x6fde577e9bfd65b9f88ee989c36e01bd1c640fc3f27ec09c5e631a747629acdb'
